# Generated by Django 5.1.1 on 2024-10-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMortalityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_of_fistula', models.IntegerField(choices=[(1, 'Sexual assault'), (2, 'Pelvic surgery'), (6, 'Other'), (8, "Don't know")], help_text='Cause of fistula')),
                ('number_of_children', models.IntegerField(help_text='Number of living children')),
                ('current_pregnancy', models.IntegerField(choices=[(0, 'No current pregnancy'), (1, '1 child'), (2, '2 children'), (3, '3 children'), (4, '4 children'), (5, '5 children'), (6, '6+ children')], help_text='Living children + Current Pregnancy')),
                ('marital_status', models.IntegerField(choices=[(0, 'Never in union'), (1, 'Currently in union/living with a man'), (2, 'Formerly in union/living with a man')], help_text='Marital status')),
                ('age_at_first_sex', models.IntegerField(choices=[(7, '7 years'), (8, '8 years'), (9, '9 years'), (10, '10 years'), (11, '11 years'), (12, '12 years'), (13, '13 years'), (14, '14 years'), (15, '15 years'), (16, '16 years'), (17, '17 years'), (18, '18 years'), (19, '19 years'), (20, '20 years'), (21, '21 years'), (22, '22 years'), (23, '23 years'), (24, '24 years'), (25, '25 years'), (26, '26 years'), (27, '27 years'), (28, '28 years'), (29, '29 years'), (30, '30 years'), (31, '31 years'), (32, '32 years'), (33, '33 years'), (34, '34 years'), (35, '35 years'), (36, '36 years'), (37, '37 years'), (38, '38 years'), (39, '39 years'), (40, '40 years'), (41, '41 years'), (42, '42 years'), (43, '43 years'), (44, '44 years'), (45, '45 years'), (46, '46 years'), (47, '47 years'), (48, '48 years'), (49, '49 years'), (0, 'Not had sex'), (96, 'At first union'), (98, "Don't know")], help_text='Age at first sexual encounter')),
                ('use_family_planning', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], help_text='Use of family planning')),
                ('education_years', models.IntegerField(help_text='Number of years of education')),
                ('entries_in_birth_history', models.IntegerField(help_text='Entries in birth history')),
                ('total_children_ever_born', models.IntegerField(help_text='Total children ever born')),
                ('ever_been_married', models.IntegerField(choices=[(0, 'No'), (1, 'Formerly married'), (2, 'Lived with a man')], help_text='Ever been married or in union')),
            ],
        ),
    ]
