# Generated by Django 5.1.1 on 2024-11-26 08:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMortalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_prediction', models.IntegerField(help_text='0 for low risk, 1 for high risk', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active Monitoring'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20)),
                ('intervention_outcome', models.CharField(blank=True, choices=[('successful', 'Successful'), ('ongoing', 'Ongoing'), ('unsuccessful', 'Unsuccessful')], max_length=20, null=True)),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.childmortalityform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Child Mortality Assessments',
            },
        ),
    ]
