# Generated by Django 5.1.1 on 2024-11-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_childmortalityassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmortalityassessment',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.childmortalityform'),
        ),
    ]
