# Generated by Django 5.1.1 on 2024-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_childmortalityassessment_form_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMRMortalityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='U5MRMortalityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.IntegerField(choices=[(0, 'No education'), (1, 'Primary'), (2, 'Secondary'), (3, 'Higher')], help_text='Highest educational level')),
                ('residence_type', models.IntegerField(choices=[(1, 'Urban'), (2, 'Rural')], help_text='Type of place of residence')),
                ('wealth_index', models.IntegerField(choices=[(1, 'Poorest'), (2, 'Poorer'), (3, 'Middle'), (4, 'Richer'), (5, 'Richest')], help_text='Wealth index')),
                ('region', models.IntegerField(choices=[(1, 'Central'), (2, 'Copperbelt')], help_text='Region')),
                ('water_source', models.IntegerField(choices=[(11, 'Piped into dwelling'), (12, 'Piped to yard/plot')], help_text='Source of drinking water')),
                ('postnatal_check', models.BooleanField(help_text='Postnatal check done')),
            ],
        ),
        migrations.RemoveField(
            model_name='childmortalityassessment',
            name='form_data',
        ),
        migrations.DeleteModel(
            name='ChildMortalityForm',
        ),
    ]
